// frontend/src/vue/App.vue
<script setup lang="ts">
import { ref } from 'vue';

const count = ref(0)
</script>

<template>
    <div class="max-w-sm mx-auto mt-40 flex items-center justify-between p-4 rounded-xl bg-green-50 text-green-500 font-thin border border-green-100">
      <p>Vue</p>
      <span>{{ count }}</span>
      <button class="text-xl" @click="count++">+</button>
    </div>
</template>

// frontend/src/spa/App.tsx
import { useState } from "react";

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="max-w-sm mx-auto mt-40 flex items-center justify-between p-4 rounded-xl bg-blue-50 text-blue-500 font-thin border border-blue-100">
      <p>React</p>
      <span>{count}</span>
      <button className="text-xl" onClick={() => setCount(count + 1)}>
        +
      </button>
    </div>
  );
}
